### ISSUE TITLE
add interface pages for RPi4 USB3 boot UAS/Trim compliance

### ISSUE THREAD

**Issue by paulwratt** [TheRemote/PiBenchmarks#10]
from the data provided by the script, this required info is already present in the db, so a page link that lists interfaces for RPi4 USB3 boot would be useful, especially to show same chipsets that work on some setups and not on others (different firmware?)

the blog page you did for this topic is still about the only "definitive" list of interface compatibility, only slightly extended if you comb through the 4 (soon to be 5) multi-page beta threads on the RPi forum: [current thread at time of posting](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=277413&start=150)

**Comment by paulwratt** [comment]
I also notice today that the field "USB Device ID" is empty, along with Model and Manufacturer (and User).

**Comment by TheRemote** [comment]
I believe this should be already fixed, but feel free to reopen if this is still happening.  You're right, the data would still be in there and it would be a parsing error (unless it's one of the chipsets that doesn't report this information).

That may be what you are talking about as well.  Some of the adapters definitely "block" some of the information from being reported for various tests.  For some of them it's hdparm, for some of them it's lshw, and some of them block all known tests altogether (there's a SSK one and a few others that I have hundreds of basically unidentifiable tests for because the adapter blocks everything I throw at it).

Definitely feel free to reopen if there's still some examples of this.  I'm trying to get this project's GitHub under control here (I've fixed it for a bunch of my other projects and am going to add checking this one to my rotation).  Thanks for the feedback!
