### ISSUE TITLE
How to remove what this installs?

### ISSUE THREAD

**Issue by QuantiumDev** [TheRemote/PiBenchmarks#11]
For those who like to keep their Pi lean and clean, it'd be nice to have a command or script that removes everything this installs.

**Comment by TheRemote** [comment]
That's a tricky one because a lot of these are core packages that are widely used.  You can absolutely bulk remove whatever it installs though with a one liner:

sudo apt remove package1 package2 package3 package4 package5 package6

On most systems it shouldn't be more than a dozen or two packages so this would definitely be the best way to remove them!

**Comment by melyux** [comment]
It should write a list somewhere of what it installed so we can know what to remove.

**Comment by TheRemote** [comment]
You can look at the source of the script and could have answered your own question a long time ago.  Here, I'll do it for you.

```
  if [ -z "$(which lshw)" ]; then apt-get install --no-install-recommends lshw -y; fi
  if [ -z "$(which lspci)" ]; then apt-get install --no-install-recommends pciutils -y; fi
  if [ -z "$(which lsusb)" ]; then apt-get install --no-install-recommends usbutils -y; fi
  if [ -z "$(which lsscsi)" ]; then apt-get install --no-install-recommends lsscsi -y; fi
  if [ -z "$(which bc)" ]; then apt-get install --no-install-recommends bc -y; fi
  if [ -z "$(which curl)" ]; then apt-get install --no-install-recommends curl -y; fi
  if [ -z "$(which hwinfo)" ]; then apt-get install --no-install-recommends hwinfo -y; fi
  if [ -z "$(which hdparm)" ]; then apt-get install --no-install-recommends hdparm -y; fi
  if [ -z "$(which dmidecode)" ]; then apt-get install --no-install-recommends dmidecode -y; fi
  if [ -z "$(which fio)" ]; then apt-get install fio -y; fi
  if [ -z "$(which iozone3)" ]; then apt-get install iozone3 -y; fi
  if [ -z "$(which nvme)" ]; then apt-get install --no-install-recommends nvme-cli -y; fi
  if [ -z "$(which smartctl)" ]; then apt-get install --no-install-recommends smartmontools -y; fi
  if [ -z "$(which sdparm)" ]; then apt-get install -no-install-recommends sdparm -y; fi
  if [ -z "$(which xxd)" ]; then apt-get install --no-install-recommends xxd -y; fi

  DpkgArch=$(dpkg --print-architecture)
  if [ -z "$(which iozone)" ]; then
    # Attempt to install iozone from package
    if [[ "$HostArchitecture" == *"armv7"* || "$HostArchitecture" == *"armhf"* ]]; then
      curl -o iozone3.deb http://ftp.us.debian.org/debian/pool/non-free/i/iozone3/iozone3_429-3+b1_armhf.deb
      dpkg --install iozone3.deb
      rm iozone3.deb
    elif [[ "$DpkgArch" == *"arm64"* || "$HostArchitecture" == *"aarch64"* || "$HostArchitecture" == *"arm64"* ]]; then
      curl -o iozone3.deb http://ftp.us.debian.org/debian/pool/non-free/i/iozone3/iozone3_429-3+b1_arm64.deb
      dpkg --install iozone3.deb
      rm iozone3.deb
    elif [[ "$DpkgArch" == *"armel"* ]]; then
      curl -o iozone3.deb http://ftp.us.debian.org/debian/pool/non-free/i/iozone3/iozone3_429-3+b1_armel.deb
      dpkg --install iozone3.deb
      rm iozone3.deb
    elif [[ "$HostArchitecture" == *"x86_64"* || "$HostArchitecture" == *"amd64"* ]]; then
      curl -o iozone3.deb http://ftp.us.debian.org/debian/pool/non-free/i/iozone3/iozone3_429-3+b1_amd64.deb
      dpkg --install iozone3.deb
      rm iozone3.deb
    elif [[ "$HostArchitecture" == *"i386"* ]]; then
      curl -o iozone3.deb http://ftp.us.debian.org/debian/pool/non-free/i/iozone3/iozone3_429-3+b1_i386.deb
      dpkg --install iozone3.deb
      rm iozone3.deb
    fi
  fi

```

I would honestly suggest you don't use it again as you have no clue what it is doing.  You are just running scripts from the internet with no clue what they're going to do or install?  You're not sure you want to run this?  

Please don't.  It's not meant for you.

**Comment by TheRemote** [comment]
Okay, after realizing I chewed out the wrong person I thought about this and decided I'm being unreasonable here.  I don't think trust in the script was the issue.  You guys are just asking for an easy list of ones that are safe to remove.

I've updated the script with a new section that includes these in a whole new "Removing Installed Packages" section that includes these.  The ones that are a no-brainer and safe to remove (this includes the .deb package) are:

sudo apt remove iozone3 fio

This will remove the iozone (one installed by .deb typically) and fio which are both purely disk benchmarking utilities.  Sorry for not realizing you were a completely new person.  This was what led me to ask the question am I the problem here and I think the answer is at least partially yes so I've reconsidered and added this!
