### ISSUE TITLE
Submit results error: Argument list too long

### ISSUE THREAD

**Issue by winkelement** [TheRemote/PiBenchmarks#4]
I always get the following error when running the script: `bash: line 840: /usr/bin/curl: Argument list too long`

<img width="834" alt="Bildschirmfoto 2020-01-06 um 18 19 09" src="https://user-images.githubusercontent.com/3525191/71835202-400a8f80-30b1-11ea-86a1-f5007aa3f7e6.png">

**Comment by TheRemote** [comment]
Hello,

Thanks for reporting this.  The issue was that dmesg was giving too much output which I have fixed by applying a grep usb (since we only care about the usb related dmesg messages).

Can you try again at your earliest convenience?

**Comment by winkelement** [comment]
Thanks, it's working now 👍 
Have you considered writing the results to a temp file on the local filesystem and sending this file via curl post as multipart/form-data?

**Comment by TheRemote** [comment]
Something similar is in the works!  The next version submits the hardware identification tests like lshw etc. separately from the benchmarks and the user alias/notes to help bring the character count way less than the command line.  

If the test keeps evolving and I expand it outside the Raspberry Pi I think I'll have to look at writing a temp file to the system and submitting it.

I have been trying to keep the whole test as transparent and simple as possible by using a simple web form and curl submit since it's a lot to ask to have someone run bash code on their system so I wanted everyone to be able to just look at the script and easily tell exactly what it was doing and *exactly* what information was being submitted.

I think I could keep this transparency and write the results to a temp file so I'm slowly working toward that end but in the very next update they will at least be split up into different parts!
