### ISSUE TITLE
Incorrect report

### ISSUE THREAD

**Issue by seriema** [TheRemote/PiBenchmarks#5]
Hello,

I love the idea behind this and wanted to contribute. My card showed up as a Samsung **EVO** but it's the a cheaper and simpler **Pro**.

Here's my report:
https://storage.jamesachambers.com/benchmark/6821

Here's a photo of the actual SD card (couldn't get a sharper image):
![fullsizeoutput_5343](https://user-images.githubusercontent.com/693684/72223110-e5b77600-356b-11ea-817e-783128f8dd7c.jpeg)

**Comment by seriema** [comment]
FYI: I contributed another report and it is correct.
https://storage.jamesachambers.com/benchmark/6826

**Comment by TheRemote** [comment]
Hey sariema,

Thanks for the report!  It definitely helps and I'll explain why:

Samsung's earlier SD cards (maybe 2012-2015ish?) like the Samsung Evo and Samsung Pro all come with the very helpful model name of '00000'.  Sometime after that and ever since they have given mostly separate and clear identifiable models like EB1QT, etc.

This makes identifying cards from this era very difficult.  The vast majority of the ones submitted have been the orange Samsung Evo model but there have been a few Pros.  I've been working on how to distinguish between these by things like card speed class, UHS class, etc so feedback like this helps me pull up tests and be certain it's the Pro version so I can keep improving the identification of these cards.

There are other cards like this too which I've been doing similar things to try to distinguish models.  Phison is the worst because they are a manufacturer that does not sell directly to consumers and instead sell to OEMs who rebrand it.  The problem for me is these cards still identify as "Phison" manufacturer and vendor IDs and have a very generic model like SD32G.  

Thanks again for letting me know, I'll work on distinguishing your card from the others!
