### ISSUE TITLE
fio test hangs/terminates again and again

### ISSUE THREAD

**Issue by hvdwolf** [TheRemote/PiBenchmarks#7]
Running this on my RPi3 on Raspbian Lite Buster. Before running the script I did a `sudo apt-get update; sudo apt-get upgrade.`
Next to the "normal" 32GB SD-card, a 120GB Sandisk USB-stick is inserted.

Running a sudo blkid gives me:
```
sudo blkid
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="109A-9113" TYPE="vfat" PARTUUID="e5939c4f-01"
/dev/mmcblk0p2: LABEL="32GB data" UUID="91917223-7431-4398-b36b-c648c7f784ab" TYPE="ext4" PARTUUID="e5939c4f-02"
/dev/sda1: LABEL="128GB" UUID="05c0ed6d-69dd-4324-9cff-d052b091e642" TYPE="ext4" PARTUUID="12c0f7c9-01"
/dev/mmcblk0: PTUUID="e5939c4f" PTTYPE="dos"
```

I used the command `sudo curl https://raw.githubusercontent.com/TheRemote/PiBenchmarks/master/Storage.sh | sudo bash`

Output:
```
System rootfs drive (/) has been detected as /dev/mmcblk0p2 (mmcblk0p2)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  646k  100  646k    0     0  2125k      0 --:--:-- --:--:-- --:--:-- 2132k
System:    Host: RPi3 Kernel: 4.19.97-v7+ armv7l bits: 32 compiler: gcc v: 4.9.3 Console: tty 0 
           Distro: Raspbian GNU/Linux 10 (buster) 
Machine:   Type: ARM Device System: Raspberry Pi 3 Model B Rev 1.2 details: BCM2835 rev: a02082 
           serial: <filter> 
CPU:       Topology: Quad Core model: ARMv7 v7l variant: cortex-a53 bits: 32 type: MCP arch: v7l 
           rev: 4 
           features: Use -f option to see features bogomips: 307 
           Speed: 1200 MHz min/max: 600/1200 MHz Core speeds (MHz): 1: 1200 2: 1200 3: 1200 
           4: 1200 
Graphics:  Device-1: bcm2708-fb driver: bcm2708_fb v: kernel bus ID: N/A 
           Device-2: bcm2835-hdmi driver: N/A bus ID: N/A 
           Display: server: No display server data found. Headless machine? tty: N/A 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Network:   Device-1: Standard Microsystems SMSC9512/9514 Fast Ethernet Adapter type: USB 
           driver: smsc95xx bus ID: 1-1.1:3 
           IF: eth0 state: up speed: 100 Mbps duplex: full mac: <filter> 
           IF-ID-1: wlan0 state: down mac: <filter> 
Drives:    Local Storage: total: 144.29 GiB used: 82.55 GiB (57.2%) 
           ID-1: /dev/mmcblk0 vendor: SanDisk model: SL32G size: 29.72 GiB 
           ID-2: /dev/sda type: USB vendor: SanDisk model: Ultra Fit size: 114.56 GiB 
           Message: No Optical or Floppy data was found. 
Partition: ID-1: / size: 29.09 GiB used: 10.15 GiB (34.9%) fs: ext4 dev: /dev/mmcblk0p2 
           ID-2: /boot size: 41.0 MiB used: 22.6 MiB (55.2%) fs: vfat dev: /dev/mmcblk0p1 
Info:      Processes: 154 Uptime: 1d 22m Memory: 991.6 MiB used: 482.7 MiB (48.7%) gpu: 16.0 MiB 
           Init: systemd runlevel: 5 Compilers: gcc: 8.3.0 Client: Sudo v: 1.8.27 inxi: 3.0.37 
Card CSD status register: MID: 3 OID: SD PNM: SL32G PRV: 8.0 MDATE: 7/2016
Card SCR status register: SD Physical Version Specification: 3
MicroSD information: Clock Speed: 50.0 - Manufacturer: SanDisk - Model: SL32G - Vendor: SD - Product: SD - HW Version: 0x8 - FW Version: 0x0 - Date Manufactured: 07/2016
Class: Class 10
Running HDParm tests ...
/dev/mmcblk0p2:
 Timing O_DIRECT cached reads:    44 MB in  2.01 seconds =  21.88 MB/sec
 Timing O_DIRECT disk reads:  66 MB in  3.05 seconds =  21.65 MB/sec
HDParm: 21.65 MB/s - HDParmCached: 21.88 MB/s
Running dd tests ...
81920+0 records in
81920+0 records out
335544320 bytes (336 MB, 320 MiB) copied, 22.7618 s, 14.7 MB/s
DD Write Speed: 14.7 MB/s
Running fio write test ...
fio: job startup hung? exiting.
fio: 1 job failed to start
Terminated
```

Running the fiowrite by hand gives me the same error:
```
fio4kRandWrite=$(fio --minimal --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=80M --readwrite=randwrite | sed 's/;/!/g')
fio: job startup hung? exiting.
fio: 1 job failed to start
```
Identical for the fioread:
```
fio4kRandRead=$(fio --minimal --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=80M --readwrite=randread | sed 's/;/!/g')

fio: job startup hung? exiting.
fio: 1 job failed to start
```

**Comment by TheRemote** [comment]
This is not something I've seen reported yet in the 5000+ benchmarks people have done and my initial thought would definitely be a hardware issue.  The main suspects would be the SD card itself and the power supply powering the Pi.

Both the SD card (SanDisk Ultra) and USB stick (SanDisk Ultra Fit) are very common and have been benchmarked many times already.  It looks like it is testing the SD card from the lines indicating /dev/mmcblk0p2 so that would be my primary guess.

The reason I also mentioned the power adapter is it's one of the most frequent causes of issues like this but it's the last thing anyone thinks of when troubleshooting.  Some power adapters struggle when they are fully loaded especially with extra USB devices plugged in.  You may want to try without any USB devices plugged in and just testing the SD card only and see if you experience any hang without them plugged in.  

Any alternative power supply you could test with is also a very good test.  You can even power the Pi from a PC port through a regular USB to micro USB cable as an alternative to using an existing power supply.

I can just say that it's a very unusual error especially for Raspbian and an RPI 3 which is a very common configuration and it indicates we are having some sort of problem with power or hardware.

**Comment by hvdwolf** [comment]
I will check. It is a 2.4 USB power supply (and not a cheap Chinese one). I will get my new Rpi 4B this weekend and wanted to do some tests before and after.
It is a headless server config.
There is however a webcam and an arduino plugged in. I will remove them to test.

**Comment by hvdwolf** [comment]
I did check without the Arduino and without the webcam. Now it functions fine.
Sorry to cause confusion with a "bug" when it was some configuration issue.
